### ISSUE TITLE
Outdated instructions for launching moveit_rviz.launch

### ISSUE THREAD

**Issue by ljden** [fmauch/universal_robot#11]
The readme still says to run the moveit_rviz.launch with config:=true, however the interface has changed with the recent updates:
https://github.com/fmauch/universal_robot/blob/09a637d534dd958dda47d6d56b077dda7e67eef8/ur5e_moveit_config/launch/moveit_rviz.launch#L7-L9

From https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/403#issuecomment-861435133 it seems like `config:=true` should be `config:=$(rospack find ur5_moveit_config)/launch/moveit.rviz`

I will open a separate issue regarding moveit.rviz defaulting to the endeffector group rather than manipulator

**Comment by fmauch** [comment]
The main README file has indeed not been touched, yet and should get some overhaul.

**Comment by fmauch** [comment]
This is covered upstream and should be covered by https://github.com/ros-industrial/universal_robot/pull/538
