### ISSUE TITLE
moevit.rviz has confusing defaults for beginners 

### ISSUE THREAD

**Issue by ljden** [fmauch/universal_robot#12]
Opening the moveit.rviz file will by default open with the Planning Group set to endeffector rather than manipulator. This means the TCP of the robot cannot be dragged around to plan a motion. This is confusing to beginners why don't understand all the parts.

I also noticed that there was a large diff between the moveit.rviz file before and after opening it and changing the Planning Group to manipulator https://pastebin.com/UkrCVB3C

**Comment by fmauch** [comment]
That's a good point. Changing this might help a lot of beginners.

**Comment by ljden** [comment]
A minor thing but the default behaviour of the Planned Path changed so the animation now continually loops. Several students found this confusing/frustrating/distracting. Any strong opinions on changing it to not loop?
  
https://github.com/fmauch/universal_robot/blob/63914669beefd30c03301ea09101c9cafd6752a2/ur5e_moveit_config/launch/moveit.rviz#L328

**Comment by fmauch** [comment]
As looping is the default setting, I would leave it at that.

**Comment by ljden** [comment]
Fair call, thanks for the quick responses
