### ISSUE TITLE
outdated instructions for launching gazebo

### ISSUE THREAD

**Issue by ljden** [fmauch/universal_robot#13]
README suggests to launch gazebo with ur5e.launch, this is now ur5e_bringup.launch as per aac8d2db11fb6ea1f3064bb11a8e6a8636efec1e

https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/419

**Comment by fmauch** [comment]
as with #11 the toplevel README needs some work

**Comment by fmauch** [comment]
This is fixed upstream: https://github.com/ros-industrial/universal_robot/tree/melodic-devel-staging
