### ISSUE TITLE
Upgrade Boost include directories for `ur_kinematics`

### ISSUE THREAD

**Issue by stefanscherzinger** [fmauch/universal_robot#17]
**Branch**: calibration_devel
**Use case**: The issue came up [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/issues/432#issuecomment-895387436).

**Problem statement**:

The `ur_kinematics` package seems to use Boost includes via [`include_directories(SYSTEM ${Boost_INCLUDE_DIR})`](https://github.com/fmauch/universal_robot/blob/calibration_devel/ur_kinematics/CMakeLists.txt#L26), which is a `cache entry`. 

I'm not sure, though, why and how `ur_kinematics` would drop the own generation of such `cache entries` in that case, despite the package's
```bash
find_package(Boost REQUIRED COMPONENTS system)
```

**Possible solution**:
Use the `result variable` instead, as recommended [here](https://cmake.org/cmake/help/latest/module/FindBoost.html#hints).
```bash
include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
```

**Comment by fmauch** [comment]
Let me come back to this later...

**Comment by fmauch** [comment]
This issue should be migrated to the upstream repo. As `ur_kinematics` needs some attention, anyway this might be a relevant point to consider.

**Comment by fmauch** [comment]
Closing in favor of https://github.com/ros-industrial/universal_robot/issues/603
