### ISSUE TITLE
How to change the planning frame in moveit to make it match the base frame definition on the UR robot

### ISSUE THREAD

**Issue by taochenshh** [fmauch/universal_robot#23]
Hi,

I am trying to use the new [UR robot driver](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver). But it seems that the planning frame used in the Moveit is "base_link", which has a different frame definition compared to the one used on the UR robot. "base" frame matches the frame definition on the real UR robot. I tried to change the base_link in this [line](https://github.com/fmauch/universal_robot/blob/calibration_devel/ur5e_moveit_config/config/ur5e.srdf#L13) to 'base' or 'base_link_inertia". However, this does not change the planning reference frame used in Moveit. How can I change the reference frame? Thanks.

**Comment by fmauch** [comment]
If still relevant, please reopen the issue at the upstream repo in ros_industrial. Since https://github.com/ros-industrial/universal_robot/pull/538 is merged, I will no longer actively maintain this repo.
